# Generated by Django 5.2.5 on 2025-09-17 18:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrainement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name="Nom de l'entrainement")),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Entrainement',
                'verbose_name_plural': 'Entrainements',
                'ordering': ['nom'],
            },
        ),
        migrations.RenameField(
            model_name='exercice',
            old_name='reps',
            new_name='reps_sugg',
        ),
        migrations.RenameField(
            model_name='exercice',
            old_name='series',
            new_name='series_sugg',
        ),
        migrations.CreateModel(
            name='ExerciceEntrainement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sets personnalisés')),
                ('reps', models.PositiveIntegerField(blank=True, null=True, verbose_name='Répétitions personnalisées')),
                ('entrainement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_web.entrainement')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_web.exercice')),
            ],
            options={
                'verbose_name': "Exercice dans l'entraînement",
                'verbose_name_plural': 'Exercices dans les entraînements',
                'ordering': ['entrainement', 'exercice'],
                'unique_together': {('entrainement', 'exercice')},
            },
        ),
        migrations.AddField(
            model_name='entrainement',
            name='exercices',
            field=models.ManyToManyField(blank=True, through='site_web.ExerciceEntrainement', to='site_web.exercice', verbose_name='Exercices'),
        ),
    ]
