# Generated by Django 5.2.5 on 2025-09-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0002_alter_user_taille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='taille',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name="Taille de l'utilisateur"),
        ),
    ]
