# Generated by Django 5.2.5 on 2025-09-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0002_entrainement_rename_reps_exercice_reps_sugg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name="Poids de l'utilisateur"),
        ),
        migrations.AlterField(
            model_name='user',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='taille',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name="Taille de l'utilisateur"),
        ),
    ]
