# Generated by Django 5.2.5 on 2025-09-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0003_alter_user_avatar_alter_user_date_naissance_and_more'),
        ('site_web', '0003_alter_user_taille'),
    ]

    operations = [
    ]
