# Generated by Django 5.2.5 on 2025-09-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0004_merge_20250924_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='taille',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=3, verbose_name="Taille de l'utilisateur"),
            preserve_default=False,
        ),
    ]
