# Generated by Django 5.2.5 on 2025-09-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0005_alter_user_taille'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='est_approuve',
            field=models.BooleanField(default=False),
        ),
    ]
