# Generated by Django 5.2.5 on 2025-09-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0006_exercice_est_approuve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='taille',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name="Taille de l'utilisateur"),
        ),
    ]
