# Generated by Django 5.2.5 on 2025-09-29 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0007_alter_user_taille'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrainement',
            name='createur',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='proposed_exercices', to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
    ]
