# Generated by Django 5.2.5 on 2025-09-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0008_entrainement_createur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercice',
            options={'ordering': ['nom', 'groupe_musculaire'], 'verbose_name': 'Exercice', 'verbose_name_plural': 'Exercices'},
        ),
    ]
