# Generated by Django 5.2.5 on 2025-10-17 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0009_alter_exercice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='description',
            field=models.CharField(max_length=400, validators=[django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(400)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
