# Generated by Django 5.2.5 on 2025-10-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0010_alter_exercice_description_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icone', models.ImageField(upload_to='badges/icones/')),
                ('categorie', models.CharField(choices=[('FORCE', 'Force'), ('ENDURANCE', 'Endurance'), ('ASSIDUITE', 'Assiduité'), ('TECHNIQUE', 'Technique'), ('NUTRITION', 'Nutrition'), ('AUTRE', 'Autre')], max_length=50)),
                ('code', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['nom'],
            },
        ),
    ]
