# Generated by Django 5.2.5 on 2025-10-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0011_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='code',
            field=models.SlugField(error_messages={'unique': 'Un badge avec ce code existe déjà. Choississez un autre nom ou laissez le champ vide pour générer automatiquement le code.'}, unique=True),
        ),
    ]
