# Generated by Django 5.2.5 on 2025-10-29 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0012_alter_badge_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_effectues', models.PositiveIntegerField(default=0, verbose_name='Séries effectués')),
                ('reps_effectuees', models.PositiveIntegerField(default=0, verbose_name='Répétitions effectuées')),
                ('entrainements_completes', models.PositiveIntegerField(default=0, verbose_name='Entraînements complétés')),
                ('exercices_completes', models.PositiveIntegerField(default=0, verbose_name='Exercices complétés')),
                ('badges_obtenus', models.PositiveIntegerField(default=0, verbose_name='Badges obtenus')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'ordering': ['exercices_completes'],
            },
        ),
    ]
