# Generated by Django 5.2.5 on 2025-10-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0013_statistique'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistique',
            new_name='Statistiques',
        ),
    ]
