# Generated by Django 5.2.5 on 2025-11-03 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0014_rename_statistique_statistiques'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefiBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_web.badge')),
            ],
        ),
        migrations.CreateModel(
            name='Defis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du défi')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateTimeField(help_text='Date à laquelle le défi doit être terminé.', verbose_name='Date limite de complétion')),
                ('badges', models.ManyToManyField(through='site_web.DefiBadge', to='site_web.badge')),
            ],
            options={
                'verbose_name': 'Défi',
                'verbose_name_plural': 'Défis',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='defibadge',
            name='defi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_web.defis'),
        ),
        migrations.AlterUniqueTogether(
            name='defibadge',
            unique_together={('defi', 'badge')},
        ),
        migrations.CreateModel(
            name='UserBadgeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_complete', models.BooleanField(default=False)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_web.badge')),
                ('defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_web.defis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
