# Generated by Django 5.2.5 on 2025-11-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0015_defibadge_defis_defibadge_defi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defis',
            name='date_limite',
            field=models.DateTimeField(verbose_name='Date limite de complétion'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadgeprogress',
            unique_together={('user', 'badge', 'defi')},
        ),
    ]
