# Generated by Django 5.2.5 on 2025-11-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0016_alter_defis_date_limite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='condition_param',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Paramètre de la condition (ex: ID du défi ou nombre de défis)'),
        ),
        migrations.AddField(
            model_name='badge',
            name='condition_type',
            field=models.CharField(choices=[('DEFI', 'Compléter un défi spécifique'), ('NB_DEFIS', 'Compléter un certain nombre de défis')], default='DEFI', max_length=20, verbose_name='Type de condition pour obtenir ce badge'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badge',
            name='categorie',
            field=models.CharField(blank=True, choices=[('FORCE', 'Force'), ('ENDURANCE', 'Endurance'), ('ASSIDUITE', 'Assiduité'), ('TECHNIQUE', 'Technique'), ('NUTRITION', 'Nutrition'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50, verbose_name='Catégorie du badge'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='code',
            field=models.SlugField(blank=True, help_text="Identifiant unique (généré automatiquement à partir du nom s'il est laissé vide).", unique=True),
        ),
    ]
