# Generated by Django 5.2.5 on 2025-11-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0018_alter_badge_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='condition_param',
            field=models.CharField(default=1, max_length=100, verbose_name='Paramètre de la condition (ex: ID du défi ou nombre de défis)'),
            preserve_default=False,
        ),
    ]
