# Generated by Django 5.2.5 on 2025-11-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0019_alter_badge_condition_param'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='condition_param',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='condition_type',
        ),
        migrations.AddField(
            model_name='badge',
            name='seuil',
            field=models.PositiveIntegerField(default=1, verbose_name='Seuil à atteindre pour obtenir ce badge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='stat_cible',
            field=models.CharField(choices=[('REPS', 'Répétitions totales'), ('SETS', 'Séries totales'), ('EXOS', 'Exercices complétés'), ('WORKOUTS', 'Entraînements complétés')], default=1, max_length=20, verbose_name='Statistique ciblée pour ce badge'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badge',
            name='code',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
