# Generated by Django 5.2.5 on 2025-11-18 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0021_userbadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_complete', models.BooleanField(default=False)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='site_web.defis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defis_utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Défi utilisateur',
                'verbose_name_plural': 'Défis utilisateurs',
                'unique_together': {('user', 'defi')},
            },
        ),
    ]
