# Generated by Django 5.2.5 on 2025-11-18 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0022_userdefi'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_web.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slot'],
                'unique_together': {('user', 'slot')},
            },
        ),
    ]
