# Generated by Django 5.2.5 on 2025-11-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0023_badgeequipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistiques',
            name='defis_completes',
            field=models.PositiveIntegerField(default=0, verbose_name='Défis complétés'),
        ),
    ]
