# Generated by Django 5.2.5 on 2025-11-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0024_statistiques_defis_completes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistiques',
            name='defis_completes',
        ),
    ]
