# Generated by Django 5.2.5 on 2025-12-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0026_alter_badge_icone_alter_exercice_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='stat_cible',
            field=models.CharField(choices=[('RÉPÉTITIONS', 'Répétitions totales'), ('SÉRIES', 'Séries totales'), ('EXERCICES', 'Exercices complétés'), ('ENTRAÎNEMENTS', 'Entraînements complétés')], max_length=20, verbose_name='Statistique ciblée pour ce badge'),
        ),
    ]
