# Generated by Django 5.2.5 on 2025-12-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0027_alter_badge_stat_cible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='categorie',
            field=models.CharField(choices=[('FORCE', 'Force'), ('ENDURANCE', 'Endurance'), ('ASSIDUITE', 'Assiduité'), ('TECHNIQUE', 'Technique'), ('AUTRE', 'Autre')], max_length=50, verbose_name='Catégorie du badge'),
        ),
    ]
